'\" t
.\"     Title: ascii
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.16
.\"      Date: 2024-02-07
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "ASCII" "1" "2024-02-07" "\ \&" "\ \&"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
ascii \- report character aliases
.SH "SYNOPSIS"
.sp
\fBascii\fP [\-d] [\-x] [\-o] [\-h] [\-v] [char\-alias]
.SH "OPTIONS"
.sp
Called with no options, ascii behaves like
"ascii \-h".  Options are as follows:
.sp
\-t
.RS 4
Script\-friendly mode, emits only ISO/decimal/hex/octal/binary
encodings of the character.
.RE
.sp
\-s
.RS 4
Parse multiple characters.  Convenient way of parsing strings.
.RE
.sp
\-a
.RS 4
Print in vertical aspect (4 columns by 16 rows) rather than
16x4. This option combines only with \-d \-o \-x \-b and must precede them.
.RE
.sp
\-d
.RS 4
Ascii table in decimal.
.RE
.sp
\-x
.RS 4
Ascii table in hex.
.RE
.sp
\-o
.RS 4
Ascii table in octal.
.RE
.sp
\-b
.RS 4
Ascii table in binary.
.RE
.sp
\-h, \-?
.RS 4
Show summary of options and a simple ASCII table.
.RE
.sp
\-v
.RS 4
Show version of program.
.RE
.SH "DESCRIPTION"
.sp
Characters in the ASCII set can have many aliases, depending on
context. A character\(cqs possible names include:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Its bit pattern (binary representation).
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Its hex, decimal and octal representations.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Its teletype mnemonic and caret\-notation form (for control
chars).
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Its backlash\-escape form in C (for some control chars).
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Its printed form (for printables).
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Its full ISO official name in English.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Its ISO/ECMA code table reference.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Its name as an HTML/SGML entity.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Slang and other names in wide use for it among hackers.
.RE
.sp
This utility accepts command\-line strings and tries to interpret them
as one of the above.  When it finds a value, it prints \fIall\fP of the
names of the character.  The constructs in the following list can be
used to specify character values.  If an argument could be interpreted
in two or more ways, names for all the different characters it might
be are dumped.
.sp
\fIcharacter\fP
.RS 4
Any character not described by one of the following conventions
represents the character itself.
.RE
.sp
^\fIcharacter\fP
.RS 4
A caret followed by a character.
.RE
.sp
\(rs[abfnrtv0]:
A backslash followed by certain special characters (abfnrtv).
.sp
\fImnemonic\fP
.RS 4
An ASCII teletype mnemonic.
.RE
.sp
\fIhexadecimal\fP
.RS 4
A hexadecimal (hex) sequence consists of one or two
case\-insensitive hex digit characters (01234567890abcdef). To ensure
hex interpretation use one of the prefixws h, 0x, x, or \(rsx.
.RE
.sp
\fIdecimal\fP
.RS 4
A decimal sequence consists of one, two or three decimal digit
characters (0123456789). To ensure decimal interpretation use one of
the prefixes d, 0d, or \(rsd.
.RE
.sp
\fIoctal\fP
.RS 4
An octal sequence consists of one, two or three octal digit
characters (01234567).  To ensure octal interpretation use one of
the prefixes 0o, o, or \(rso.
.RE
.sp
\fIbit pattern\fP
.RS 4
A bit pattern (binary) sequence consists of one to eight binary
digit characters (01).  To ensure bit interpretation use one of the
prefxes 0bm b, or \(rsb.
.RE
.sp
\fIISO/ECMA code\fP
.RS 4
An ISO/ECMA code sequence consists of one or two decimal digit
characters, a slash, and one or two decimal digit characters.
.RE
.sp
\fIname\fP
.RS 4
An official ASCII or (unofficial) slang name.
.RE
.sp
:\fIclass\fP:
.RS 4
A named POSIX character class.
.RE
.sp
The slang names recognized and printed out are from a rather
comprehensive list that first appeared on USENET in early 1990 and has
been continuously updated since.  Mnemonics recognized and printed
include the official ASCII set, some official ISO names (where those
differ) and a few common\-use alternatives (such as NL for LF).
HTML/SGML entity names are also printed when applicable.  All
comparisons are case\-insensitive, and dashes are mapped to spaces.
Any unrecognized arguments or out of range values are silently
ignored.  Note that the <option>\-s</option> option will not recognize
"long" names, as it cannot differentiate them from other parts of the
string.
.sp
For correct results, be careful to stringize or quote shell
metacharacters in arguments (especially backslash).
.sp
This utility is particularly handy for interpreting cc(1)\*(Aqs ugly
octal "invalid\-character" messages, or when coding anything to do with
serial communications.  As a side effect it serves as a handy
base\-converter for random 8\-bit values.
.SH "AUTHOR"
.sp
Eric S. Raymond \c
.MTO "esr\(atthyrsus.com" "" ";"
November 1990 (home page at
>\c
.URL "http://www.catb.org/~esr/" "" ")."
Ioannis E. Tambouras <
.MTO "ioannis\(atdebian.org" "" ">"
added command options and minor enhancements.  Brian J. Ginsbach
\c
.MTO "ginsbach\(atsgi.com" "" ""
fixed several bugs and expanded the man page.
David N. Welton \c
.MTO "davidw\(atefn.org" "" ""
added the <option>\-s</option> option.
Matej Vela corrected the ISO names.  Dave Capella contributed the idea
of listing HTML/SGML entities.